spring:
  application:
    name: MSInventario

# Configuraci√≥n de SpringDoc OpenAPI / Swagger
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    disable-swagger-default-url: true
    urls:
      - name: MS Inventario (8080)
        url: http://localhost:8080/api-docs
      - name: API Gateway (8093)
        url: http://localhost:8093/api-docs
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
